# Generated by Django 4.1.5 on 2023-03-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_mytodos_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodos',
            name='task',
            field=models.TextField(max_length=100),
        ),
    ]
