# Generated by Django 4.1.5 on 2023-01-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInformation',
        ),
    ]
