# Generated by Django 4.1.5 on 2023-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namees', models.CharField(max_length=50)),
                ('reserv_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField(max_length=30)),
            ],
        ),
    ]
