# Generated by Django 4.1.5 on 2023-02-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_bookinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=100)),
                ('home_cell', models.CharField(max_length=50)),
                ('vertual_church', models.CharField(max_length=50)),
                ('pastor_name', models.CharField(max_length=40)),
                ('date_joined', models.DateField()),
            ],
        ),
    ]
