# Generated by Django 4.1.5 on 2023-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_church'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smoothie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=40)),
                ('prod_name', models.CharField(max_length=100)),
                ('discrption', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=300)),
            ],
        ),
    ]
