# Generated by Django 4.1.5 on 2023-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_smoothie'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
