# Generated by Django 4.1.5 on 2023-03-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_smoothie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smoothie',
            name='picture',
        ),
    ]
