# Generated by Django 4.1.5 on 2023-03-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_alter_order_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
