# Generated by Django 4.1.5 on 2023-03-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
