# Generated by Django 4.1.5 on 2023-03-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='create',
        ),
    ]
