# Generated by Django 4.1.5 on 2023-03-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_remove_order_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
