# Generated by Django 4.1.5 on 2023-04-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('card_details', models.IntegerField(max_length=100)),
                ('amount_paid', models.IntegerField(max_length=100)),
            ],
        ),
    ]
