# Generated by Django 4.1.5 on 2023-04-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_alter_backend_card_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackEnd',
        ),
    ]
