# Generated by Django 4.1.5 on 2023-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_delete_backend'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('card_details', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date_paid', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
